### PR TITLE
Unit tests, continuous integration, dev tools

### LINKED ISSUE #31: Setup unit tests
- [Testing documentation](https://golang.org/pkg/testing/)
- [Mocking](https://stackoverflow.com/questions/19167970/mock-functions-in-go)

### LINKED ISSUE #32: Continuous Integration
dependent on #31

Travis should:
- [x] Set up ENV
- [x] Set up [test database](https://docs.travis-ci.com/user/database-setup/#PostgreSQL)
- [x] Run unit tests
- [x] Report coverage to coveralls/codecov

### PR DESCRIPTION
**Pull request by bobheadxi**
### Related Issues
Closes #31 - Unit tests
Closes #32 - Continuous integration

### Description
- 🔨 Unit tests! 

- 📁 ~~Set up testing directory - tests should go under package `tests` and file names should be suffixed with `_test.go`, function names should be prefixed with `Test`~~

- 🎉 ~~Added unit test for `SendTextMessage()` and `facebook.New()`~~

- 🚧 ~~Added an incomplete sample test for `bot.New`~~

- 💄 New `Makefile` for some functions to help with development:

`make` -> builds calories
`make glide` -> installs glide without needing Homebrew etc
`make deps` -> installs project dependencies
`make db` -> sets up database locally for local testing
`make deploy` -> deploys to heroku!
`make test` -> runs all tests with coverage
`make test-verbose` -> runs all tests with logs and coverage
`make clean` -> remove binary (that's it for now)

- 👶  Travis (runs tests, sets up mock database) and coveralls (for code coverage)

### Todos
- [x] Tests for package `facebook`
- [x] Tests for package `bot`
- [x] Tests for package `server`
- [x] Tests for package `config`
- [x] Get travis running
- [x] Update README and Wiki for new Makefile ([wiki changes](https://github.com/bobheadxi/calories/wiki/Heroku-Usage-for-Collaborators))

### Notes
- Run the tests using:
```
make test
```

- Might be best to test by package instead of file. Our goal is hopefully to have tests for all top-level public functions (ie not helper functions like `facebook.api.makeRequest()`, but definitely do test a public function like `facebook.api.SendTextMessage()`)

- A test should only use functions from within the package being tested. There might be some things that seem impossible to isolate - see the next point

- Try to make minimal changes to the functional code - let me know if you think there's something we should change, such as to enable better package isolation. I think we are pretty well set up as far as package isolation goes, since external dependencies are typically provided via `New()` parameters, but we will probably have to make some changes, though we'll have to do some research about the best ways to do this.

- `httptest` has a lot of features that will be useful for testing, such as my usage of it in [`TestSendTextMessage`](https://github.com/bobheadxi/calories/blob/7c9c9f0af00bcce7403e8fea1e1234dc79fabbef/tests/facebook_test.go#L46). I believe it can also do things like make requests to our app so we can test our handlers and stuff. Highly recommend looking through its [documentation](https://golang.org/pkg/net/http/httptest/) and finding examples online

### CODE REVIEW

**Review by ayaMakh — COMMENTED** [review]
clean👍

**Review by bwdmonkey — COMMENTED** [review]
Looks good but I'm not sure if we should test working server and fake server in the same test. It's probably better to separate it imo.

**Comment by bobheadxi** [comment]
@ayaMakh @leesw98 @zhulia96 
As of 44fa87f, I added a handy `Makefile` for a number of actions! see the PR description 😊 

I also moved all tests into their respective packages (ie `facebook` tests are now in package `facebook`. seems easier)

**Review by bwdmonkey — COMMENTED** [review]
Having issue with ```make db```. What do?
```
sh scripts/create_db.sh
postgres (PostgreSQL) 9.6.1
MAKE: Killing existing postgres processes...
server starting
createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
LOG:  database system was shut down at 2017-12-20 19:30:22 PST
FATAL:  the database system is starting up
LOG:  MultiXact member wraparound protections are now enabled
FATAL:  the database system is starting up
createdb: could not connect to database template1: FATAL:  the database system is starting up
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "test_db" does not exist
psql: FATAL:  database "test_db" does not exist
MAKE: Local database ready to go!
```

**Comment by bobheadxi** [comment]
@leesw98 can you add ‘set -x’ to the top of the create_db script, run make db and post the console output here?

Strange because the “server starting” thing shows up but seems like something goes wrong there? How did you install Postgres?

**Comment by bobheadxi** [comment]
@leesw98 problem likely caused by how you installed postgres, or possibly not having a db set up in the place that is expected by the script - try this:
```bash
initdb /usr/local/var/postgres
```
Updated the script to run that line if you install postgres through it, but probably not the best idea to run it every time so thats it for now 😂

**Comment by bwdmonkey** [comment]
@bobheadxi here!
```
sh scripts/create_db.sh
+ postgres -V
postgres (PostgreSQL) 9.6.1
+ '[' 0 -gt 0 ']'
+ echo 'MAKE: Killing existing postgres processes...'
MAKE: Killing existing postgres processes...
+ pg_ctl -D /usr/local/var/postgres stop -s -m fast
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
+ pg_ctl -D /usr/local/var/postgres start
server starting
+ createuser -s postgres
createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
+ createdb calories_test_db
FATAL:  the database system is starting up
LOG:  database system was shut down at 2017-12-21 20:21:42 PST
LOG:  MultiXact member wraparound protections are now enabled
FATAL:  the database system is starting up
createdb: could not connect to database template1: FATAL:  the database system is starting up
+ psql -d calories_test_db -a -f ./scripts/test_db_setup.sql
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "calories_test_db" does not exist
psql: FATAL:  database "calories_test_db" does not exist
+ echo 'MAKE: Local database ready to go!'
MAKE: Local database ready to go!
```

```
The files belonging to this database system will be owned by user "leesw".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  C
  CTYPE:    UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default database encoding has accordingly been set to "UTF8".
initdb: could not find suitable text search configuration for locale "UTF-8"
The default text search configuration will be set to "simple".

Data page checksums are disabled.

initdb: directory "/usr/local/var/postgres" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/usr/local/var/postgres" or run initdb
with an argument other than "/usr/local/var/postgres".
```

**Comment by bobheadxi** [comment]
@leesw98 try installing postgres 10.1

**Comment by bobheadxi** [comment]
@leesw98 also updated the script to wait and make sure server is up before doing anything, try the latest commit

**Review by bwdmonkey — APPROVED** [review]
Nice :)

**Pull request merged**
